#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR/wsgi
python worker.py > $OPENSHIFT_PYTHON_LOG_DIR/worker.log 2>&1 &
