#!/usr/bin/python
"""
	Copyright 2013 Sérgio Berlotto <sergio.berlotto@gmail.com>

    This file is part of Scalability Generator.

    Scalability Generator is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')

if os.path.exists(os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python-2.6")):
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python-2.6")
else:
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")



virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', '2.6', 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from myflaskapp import app as application

